version: '3.8'

services:
  active_learning:
    build: ./active_learning/.
    image: al_txtl_gpu_img
    container_name: al_txtl_gpu_cntr
    ports:
      - 8882:8882
    volumes:
      - ./active_learning:/app


  horvath:
    build: ./horvath/.
    image: julia_horvath_img
    container_name: julia_horvath_ctnr
    volumes:
      - ./horvath:/app
    ports:
      - 5000:5000
    depends_on:
      - active_learning
